import { promises as fs } from "node:fs";
import path from "node:path";

import type { Locale } from "@/config/i18n";
import { contentPaths } from "./paths";

/**
 * Loading chapter MDX off disk.
 *
 * Server-only — everything here touches fs. Importing it from a client
 * component will fail at build, which is the behaviour we want.
 */

export interface TocEntry {
  /** Slug generated by rehype-slug, so it matches the rendered heading id. */
  id: string;
  text: string;
  depth: 2 | 3;
}

/** Has this chapter actually been written yet? */
export async function chapterExists(
  slug: string,
  locale: Locale = "en",
): Promise<boolean> {
  try {
    await fs.access(path.join(contentPaths.chapters(locale), `${slug}.mdx`));
    return true;
  } catch {
    return false;
  }
}

/** Slugs of every written chapter, for generateStaticParams. */
export async function listWrittenChapters(
  locale: Locale = "en",
): Promise<string[]> {
  try {
    const files = await fs.readdir(contentPaths.chapters(locale));
    return files
      .filter((f) => f.endsWith(".mdx"))
      .map((f) => f.replace(/\.mdx$/, ""));
  } catch {
    // Directory doesn't exist yet. Not an error — just nothing written.
    return [];
  }
}

async function readSource(
  slug: string,
  locale: Locale,
): Promise<string | null> {
  try {
    return await fs.readFile(
      path.join(contentPaths.chapters(locale), `${slug}.mdx`),
      "utf8",
    );
  } catch {
    return null;
  }
}

/**
 * Pulls h2/h3 out of the raw MDX for the table of contents.
 *
 * Reading the source rather than the rendered output because we need this on
 * the server before the component tree exists, and walking a compiled MDX AST
 * for three heading levels is more machinery than the job deserves.
 *
 * The slug rule has to stay in step with rehype-slug or the anchors won't
 * match. If someone swaps the slugger, this breaks quietly — worth a test
 * when the first real chapter lands.
 */
export async function getTableOfContents(
  slug: string,
  locale: Locale = "en",
): Promise<TocEntry[]> {
  const source = await readSource(slug, locale);
  if (!source) return [];

  const entries: TocEntry[] = [];
  let insideFence = false;

  for (const line of source.split("\n")) {
    // Headings inside a code fence are code, not headings.
    if (line.trimStart().startsWith("```")) {
      insideFence = !insideFence;
      continue;
    }
    if (insideFence) continue;

    const match = /^(#{2,3})\s+(.+?)\s*$/.exec(line);
    if (!match?.[1] || !match[2]) continue;

    const text = match[2]
      .replace(/`/g, "") // inline code in headings
      .replace(/\*\*?/g, "") // bold/italic markers
      .trim();

    entries.push({
      id: slugifyHeading(text),
      text,
      depth: match[1].length as 2 | 3,
    });
  }

  return entries;
}

/** Mirrors github-slugger, which is what rehype-slug uses under the hood. */
function slugifyHeading(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s-]/gu, "")
    .trim()
    .replace(/\s+/g, "-");
}

/**
 * Loads the compiled MDX component for a chapter.
 *
 * The import path is built from a template literal, which means the bundler
 * has to be able to see the directory to generate the module map — hence the
 * literal `content/en/chapters` prefix rather than interpolating the locale
 * too. Add a branch per locale when Bangla routing lands.
 */
export async function loadChapterContent(slug: string, locale: Locale = "en") {
  if (locale !== "en") return null;

  try {
    const mod = await import(`@/content/en/chapters/${slug}.mdx`);
    return {
      Content: mod.default as React.ComponentType,
      frontmatter: (mod.metadata ?? {}) as Record<string, unknown>,
    };
  } catch {
    return null;
  }
}
